
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: moma_app_development
  host: localhost
  username: straw
  password:

test:
  <<: *default
  database: moma_app_test

production:
  <<: *default
  database: moma_app_production
  username: moma_app
  password: <%= ENV['MOMA_APP_DATABASE_PASSWORD'] %>
