# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5683682588522a04fbd650ab6fb4869c91b727c58cf7777de278837058bccaba779b53e4f3202edfe326718cf3e278ddf4bdb39fc147b2b4a1fd672f0f924e9

test:
  secret_key_base: 48e3a601d9be9db5eddbd8e068a9226b6a83811acdb14497c2b2e0b40266a8db4514ea788d58b0bdf8eec799d2ae77e51903d7653065c7f4f4b131e2b8b23f1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
