# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52229e7afd8491623e0ca6a872fa85bfc0339f58ecbc492528cbaecfbef0cd8a5830d047741a27500b6d10ea5a609f9bed2c82196e226845af680d21a35c9854

test:
  secret_key_base: 0e56425c0daeb6fd962daeb76911a2ec786ad63310cdad2d71be073c949c542d2da50a9014a5c1b084a780394e0b803c5853d74d9ab9d0ee6a2f48612bcc72d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
