Author.destroy_all
Book.destroy_all

Author.create(:name => 'Andy McNab', :nationality => 'English', :dob => '1959/12/28', :image =>'http://www.thenewsgrind.com/wp-content/uploads/2010/06/andy-mcnab.jpg')
Author.create(:name => 'Micho Kaku', :nationality => 'Japanese', :dob => '1947-01-27', :image => 'http://upload.wikimedia.org/wikipedia/commons/f/fe/Michio_Kaku_in_2012.jpg')
Author.create(:name => 'J. K. Rowling', :nationality => 'English', :dob => '1965/07/31', :image =>'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTbnA1fSEYMy5wSMJq_ipY3sqylDpCVjVaQp07ovhZd77LYLC9r')

Book.create(:title => "Harry Potter and the Sorcerer's Stone", :pages => 320, :isbn =>'0439708184' , :image => 'http://www.watt-evans.com/potter1.jpg', :description =>"Harry Potter has no idea how famous he is. That's because he's being raised by his miserable aunt and uncle who are terrified Harry will learn that he's really a wizard, just as his parents were. But everything changes when Harry is summoned to attend an infamous school for wizards, and he begins to discover some clues about his illustrious birthright.")
Book.create(:title => "Harry Potter and the Chamber of Secrets", :pages => 368, :isbn =>'054558292X' , :image => 'http://upload.wikimedia.org/wikipedia/en/5/5c/Harry_Potter_and_the_Chamber_of_Secrets.jpg', :description =>"The Dursleys were so mean and hideous that summer that all Harry Potter wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he’s packing his bags, Harry receives a warning from a strange, impish creature named Dobby who says that if Harry Potter returns to Hogwarts, disaster will strike.")
Book.create(:title => "Harry Potter And The Order Of The Phoenix", :pages => 896, :isbn =>'0439358078' , :image => 'http://t0.gstatic.com/images?q=tbn:ANd9GcT1uTQXYDeyq6kX0jiJai2yjdy_QHvQUPqPyxNrelsRdOMGLY4B7Q', :description => "In his fifth year at Hogwart's, Harry faces challenges at every turn, from the dark threat of He-Who-Must-Not-Be-Named and the unreliability of the government of the magical world to the rise of Ron Weasley as the keeper of the Gryffindor Quidditch Team. Along the way he learns about the strength of his friends, the fierceness of his enemies, and the meaning of sacrifice.")
Book.create(:title => 'Parallel Worlds', :pages => '428', :isbn => '978-0385509862', :image => 'http://upload.wikimedia.org/wikipedia/en/9/97/Parallel_Worlds_Kaku_2004.jpg', :description => "In this thrilling journey into the mysteries of our cosmos, bestselling author Michio Kaku takes us on a dizzying ride to explore black holes and time machines, multidimensional space and, most tantalizing of all, the possibility that parallel universes may lay alongside our own. Kaku skillfully guides us through the latest innovations in string theory and its latest iteration, M-theory, which posits that our universe may be just one in an endless multiverse, a singular bubble floating in a sea of infinite bubble universes. If M-theory is proven correct, we may perhaps finally find answer to the question, “What happened before the big bang?” This is an exciting and unforgettable introduction into the new cutting-edge theories of physics and cosmology from one of the pre-eminent voices in the field.")
Book.create(:title => 'Remote Control', :pages => '512', :isbn => '0552163538', :image =>'http://ecx.images-amazon.com/images/I/51450Js2hZL.jpg', :description => "Tough, resourceful, ruthless - as an SAS trooper, Nick Stone was one of the best. Now he's back on the streets. After a botched mission, the Regiment no longer want his services. But British Intelligence does - as a deniable operator. It's the dirtiest job in a very, very dirty world.")