# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 536704b492546c50684b60bc0262248a57cae1ac61147662131f4adc2cece96c9509a1bdda2272787b56590e71dce87d269b4d388a3fa831122af20884ba1686

test:
  secret_key_base: 1134dce95bac9fd650b5b1cb6761b7d34f4aed9bd7bf1cd42848349b262fd1b0b4b802d63cba363f58a1be3848bc05b0462cb1a25703b96ae7073a6fbd813678

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
