
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: books_app_development
  username: Ros
  host: localhost


test:
  <<: *default
  database: books_app_test

production:
  <<: *default
  database: books_app_production
  username: Ros
  host: localhost
